### ISSUE TITLE
Can't change Tab Bar Background To Transparent

### ISSUE THREAD

**Issue by clifzero** [messier16/PlatformTabbedPage#2]
Hi 

First of all I'd like to say thank you for your wonderful plugin @fferegrino, it really is serving me.
I'm facing one problem though I can't set the BarBackgroundColor to transparent, can you please help me sort out this issue.

**Comment by fferegrino** [comment]
Following up on your [comment on the other issue](https://github.com/messier16/PlatformTabbedPage/issues/3#issuecomment-395046628), this is what I've found so far:

https://developer.apple.com/documentation/uikit/uitabbar/1623454-barstyle

And it seems like I've implemented that feature as the property `BarStyle` of `PlatformTabbedPage`, you will be able to select between `Default` and `Black` default giving you the traditional look and feel and black giving you an opaque style. 

Please be aware that it seems like if you select `Black` whites will look kind of gray... I don't seem to find a way to work around that.

I still have to publish the package to NuGet, I'll do that later today as a pre-release, can you update and test it when I do so?

**Comment by clifzero** [comment]
Thank you so much Antonio

 I really appreciate the time you take out to respond to issues.
 I'll do the best I can to assist you where I can and lift some weight off your shoulders where I can.

**Comment by fferegrino** [comment]
Hey there, here it is [PlatformTabbedPage 2.1.0-beta](https://www.nuget.org/packages/PlatformTabbedPage/2.1.0-beta), the property discussed earlier should be available now.

**Comment by clifzero** [comment]
Thank you Antonio

I'm going to have a crack at it now, just do a basic test, I guess.

**Comment by clifzero** [comment]
Okay @fferegrino  

I just ran some tests, the default BarStyle is well.... Default like one I'm currently using. 

The BarStyle.Black is more what I'm after, its actually works, its not transparent :-), but there is only one problem, the colours are too dark and inaccurate. The first test I ran was  a simple black and gold:
![simulator screen shot - iphone x - 2018-06-08 at 11 06 32](https://user-images.githubusercontent.com/18286380/41150130-966b413c-6b0d-11e8-8b7a-9a8c104b0b72.png)

Which worked perfectly. For the purpose of testing the color accuracy I got some color hexes(#ff5c33, #66ffff), in that order relative to the pictures below:

![simulator screen shot - iphone x - 2018-06-08 at 11 11 06](https://user-images.githubusercontent.com/18286380/41150285-e4b561e2-6b0d-11e8-814c-f53638962268.png)
![simulator screen shot - iphone x - 2018-06-08 at 11 12 18](https://user-images.githubusercontent.com/18286380/41150300-eb28994a-6b0d-11e8-8326-9a866a0cc76d.png)

I noticed something, the selected colour is the actual colour and the BarBackground Colour is a much darker shade of the actual color hex, its as if there's a dark shadow being place over it.

**Comment by clifzero** [comment]
Should probably drop the resolution the next time I plan on uploading images lol

**Comment by fferegrino** [comment]
Yes, the colours are not accurate, iOS seems to mess with the "dark" colours when using the `Default` option and messes with the "clear" colors when set to `Black`... I guess is a matter of trial and error for now.

**Comment by clifzero** [comment]
@fferegrino  I made some changes  that you might just like, I cloned the project and played around a bit, but I can't seem to create a PR because you only have a master branch and I don't have access to it, so I can't commit either.

**Comment by clifzero** [comment]
I'm such a GitHub Noob though haha, just found out recently that I can fork your repository, make changes to the fork and then use that to create a pull request.

**Comment by fferegrino** [comment]
Perfect, I've published your changes as [2.2.0-beta](https://www.nuget.org/packages/PlatformTabbedPage/2.2.0-beta). I'll now close this issue and if there is something to discuss about that just open a new one.

Thanks for your contribution.

**Comment by clifzero** [comment]
@fferegrino  You're welcome Antonio, I still see some potential for a few more customisability options
though ;).
